carts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from carts import views

app_name = 'cart'

urlpatterns = [
    url(r'^cart_home/$', views.home, name='cart_home'),
    url(r'^event_add/$', views.event_add, name='event_add'),
    # url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_status/(?P<status_id>[0-9]+)/$', views.watch_status, name='watch_status'),
    url(r'^watch_place/(?P<place_id>[0-9]+)/$', views.watch_place, name='watch_place'),
    url(r'^watch_model/(?P<model_id>[0-9]+)/$', views.watch_model, name='watch_model'),
    url(r'^homecoming/(?P<num_id>[0-9]+)/$', views.homecoming, name='homecoming'),
    url(r'^send_refill/(?P<num_id>[0-9]+)/$', views.send_refill, name='send_refill'),
    url(r'^test/$', TemplateView.as_view(template_name="test.html")),
    url(r'^cart_home/group_ops/$', views.group_ops, name='group_ops'),
    url(r'^cart_home/get_group_ops/$', views.get_group_ops, name='get_group_ops'),
    url(r'^cart_home/get_swap/$', views.get_swap, name='get_swap'),
    # url(r'^cart_home/get_swap/(?P<num>[0-9]+)/$', views.get_swap, name='get_swap'),
]

ticket/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from ticket import views

app_name = 'ticket'

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^thanks/$', TemplateView.as_view(template_name="thanks.html")),
    url(r'^test/$', views.test, name='test'),
    url(r'^delete_row/(?P<ticket_id>[0-9]+)/$', views.delete_row, name='delete_row'),
    url(r'^all/$', views.watch_all, name='watch_all'),
    url(r'^my_tickets/$', views.my_tickets, name='my_tickets'),
    url(r'^watch/(?P<ticket_id>[0-9]+)/$', views.watch_one, name='watch_one'),
    url(r'^history/$', views.history, name='history'),
    url(r'^ticket_add/$', views.send_ticket, name='ticket_add'),
    url(r'^finish/(?P<ticket_id>[0-9]+)/$', views.finish, name='finish'),
    url(r'^confirm/(?P<ticket_id>[0-9]+)/$', views.confirm, name='confirm'),
]

tickets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('loginsys.urls', namespace='loginsys')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^tickets/', include('ticket.urls')),
    url(r'^video/', views.you_tube, name='you_tube'),
    url(r'^macmap/', include('macmap.urls')),
    url(r'^', views.main),
] # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/models.py
from django.db import models


class Tickets(models.Model):
    who = models.CharField(max_length=150)
    subject = models.TextField()
    where = models.CharField(max_length=200)
    when = models.DateTimeField(auto_now=False)  # Date when ticket was created
    date_end = models.DateTimeField(auto_now=False, null=True)  # Date when ticket is done
    date_confirm = models.DateTimeField(auto_now=False, null=True) # Date of confirmation
    confirmed = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    ip = models.CharField(max_length=50, blank=True)
    
    def __str__(self):
        return self.who

ticket/forms.py
from django import forms
from ticket.models import Tickets


class Ticket_Form(forms.ModelForm):
    class Meta:
        model = Tickets
        fields = ('who', 'where', 'subject', 'ip')

class Rocket_user(forms.Form):
    rocket_user = forms.CharField(label="Имя пользователя в чате", max_length=50)


ticket/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, render
from django.template.context_processors import csrf
from django.utils import timezone
from django.http import JsonResponse
from ticket.forms import Ticket_Form, Rocket_user
from ticket.models import Tickets
from django.contrib import auth
from requests import get
from ticket.Test_bot import rocket_confirm

send_message = "https://api.telegram.org/bot2038916948:AAHi4gfEQcZkS8Ql84x_DzoIFt2lXBx0ZzQ/sendMessage?chat_id=-1001589165256&text="


# Показ домашней странички с формой ввода тикета
def home_page(request):
    add_form = Ticket_Form
    args = {}
    args.update(csrf(request))
    args['form'] = add_form
    args['username'] = auth.get_user(request).username
    args['url_name'] = request.resolver_match.url_name
    return render_to_response('home.html', args)


# Экшн отправки и сохраненя формы в базу
def send_ticket(request):
    try:
        if request.method == 'POST':
            form = Ticket_Form(request.POST)
            if form.is_valid:
                x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

                if x_forwarded_for:
                    ip = x_forwarded_for.split(',')[0]
                    print("ip1=", ip)
                else:
                    ip = request.META.get('REMOTE_ADDR')
                    print()
                ticket = form.save(commit=False)
                ticket.ip = ip
                ticket.when = timezone.now()
                ticket.save()  # Сохраняем тикет в базу

                message = request.POST.get("who") + " " + \
                          request.POST.get("where") + " " + \
                          request.POST.get("subject")
                try:
                    print(send_message + message)
                    get(send_message + message)  # Отправить текст сообщения в телеграмм
                except:
                    pass

    except ObjectDoesNotExist:
        raise Http404
    return HttpResponseRedirect('/tickets/thanks/')
    # data = {"is_taken": "Good"}
    # return JsonResponse(data)


# Админам смотреть список всех заявок
@login_required
def watch_all(request):
    args = {'tickets': Tickets.objects.filter(deleted=False).order_by('-when'),
            'username': auth.get_user(request).username,
            'url_name': request.resolver_match.url_name,
            'form': Rocket_user}
    args.update(request)
    return render_to_response('watch_all.html', args)


# Показать пользователям их заявки
def my_tickets(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    args = {'tickets': Tickets.objects.filter(ip=ip).order_by('-when'),
            'username': auth.get_user(request).username,
            'url_name': request.resolver_match.url_name,
            'form': Rocket_user
            }
    args.update(request)
    return render_to_response('my_tickets.html', args)


@login_required
def history(request):
    args = {'tickets': Tickets.objects.filter(deleted=True).order_by('-when'),
            'username': auth.get_user(request).username,
            'url_name': request.resolver_match.url_name}
    return render_to_response('history.html', args)


# Смотреть одну заявку
@login_required
def watch_one(request, ticket_id):
    args = {'ticket': Tickets.objects.get(id=ticket_id),
            }
    args.update(csrf(request))
    return render_to_response('watch_one.html', args)


# Экшн принятия заявки в работу
def confirm(request, ticket_id):
    try:
        selected_ticket = Tickets.objects.get(id=ticket_id)
        if not selected_ticket.confirmed:
            selected_ticket.confirmed = True
            selected_ticket.date_confirm = timezone.now()
        elif selected_ticket.confirmed:
            selected_ticket.confirmed = False
        selected_ticket.save()
    except ObjectDoesNotExist:
        raise Http404
    return HttpResponseRedirect('/tickets/all/')


# Экшн подтверждения выполнения и архивации заявки
def finish(request, ticket_id):
    try:
        selected_ticket = Tickets.objects.get(id=ticket_id)
        if not selected_ticket.finished:
            selected_ticket.finished = True
            selected_ticket.deleted = True
            selected_ticket.confirmed = True
            selected_ticket.date_end = timezone.now()
            print(1)
        elif selected_ticket.finished:
            selected_ticket.confirmed = True
            selected_ticket.finished = False
            print(2)
        selected_ticket.save()
    except ObjectDoesNotExist:
        raise Http404
    if request.method == "POST":
        name = request.POST.get("rocket_user")
        text = selected_ticket.subject
        rocket_confirm(ticket_id, text, name)
    return HttpResponseRedirect('/tickets/all/')


# Экшн "Архивирования" записи
def delete_row(request, ticket_id):
    try:
        selected_ticket = Tickets.objects.get(id=ticket_id)
        selected_ticket.finished = True
        selected_ticket.deleted = True
        selected_ticket.confirmed = True
        selected_ticket.save()
    except ObjectDoesNotExist:
        raise Http404
    return HttpResponseRedirect('/tickets/all/')


def test(request):
    count = Tickets.objects.filter(confirmed=False)
    return JsonResponse({"tickets_count": count.__len__()})

ticket/templates/d_name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title></head>
<body>
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
</body>
</html>

ticket/templates/history.html
{% block watch_all %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/history.css' %}">
  </head> 

<div class=back_but>
    <a href="/"><input class="back" type="submit" value="Вернуться в главное меню"/></a>
</div>
<div class="base">
  <table class="table">
    <thead class="table_head">
      <tr>
        <th class="col-1">Номер</th>
        <th class="col-1">ID заявки</th>
        <th class="col-1">Отправитель</th>
        <th class="col-1">Место</th>
        <th class="col-1">Дата поступления</th>
        <th class="col-2">Subject</th>
      </tr>
    </thead>
    <tbody class="table_body">
    {% for ticket in tickets %}
      <tr>
        <td class="col-1">{{ forloop.counter }}</td>
        <td class="col-1">{{ ticket.id }}</td>
        <td class="col-1">{{ ticket.who }}</td>
        <td class="col-1">{{ ticket.where }}</td>
        <td class="col-1">{{ ticket.when }}</td>
        <td class="col-2"><a href="{% url 'ticket:watch_one' ticket_id=ticket.id %}">{{ ticket.subject }}</a></td>
       </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

ticket/templates/home.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>tecket</title>
    <link rel="stylesheet" href="{% static '/css/ticket.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
  </head> 

{% block form %}

    <div class="back_but">
        <a href="/">
            
                <input class="back" type="submit" value="Вернуться в главное меню"/>
            
        </a>
    </div>
    
    <div class="home_page">
        <form action="{% url 'ticket:ticket_add' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="input-lg">
               <input type="text" name="who" id="id_who" placeholder="ИМЯ, ФАМИЛИЯ" required>
                {{ form.who.errors }}
                <!--  {{ form.who }}  --> 
            </div>
            <div class="input-lg">
                <input type="text" name="where" id="id_where" placeholder="ВАШ ОТДЕЛ" required> 
                {{ form.where.errors }}
                <!--  {{ form.where }}  -->
            </div>
            <div class="problem">
                <textarea id="subject" name="subject" placeholder="ОПИШИТЕ ВАШУ ПРОБЛЕМУ" cols="40" rows="7" required></textarea>
                {{ form.subject.errors }}
                <!--  {{ form.subject }}  -->
            </div>
            <div class="btn-send">
                <input class="btn btn-success" type="submit" value="ОТПРАВИТЬ ЗАЯВКУ" />
            </div>
        </form>
    </div>
  

{% endblock %}

ticket/templates/my_tickets.html
{% block my_tickets %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>active</title>
    <link rel="stylesheet" href="{% static '/css/watch_all.css' %}">
  </head>
   
<div class=back_but>
    <a href="/"><input class="back" type="submit" value="Вернуться в главное меню"/></a>
</div>
<div class="container-fluid">
  <table class="table">
    <thead class="table_head">
      <tr>
        <th class="col-1">ID заявки</th>
        <th class="col-1">Отправитель</th>
        <th class="col-1">Отдел</th>
        <th class="col-1">Дата поступления</th>
        <th class="col-1">Дата завершения</th>
        <th class="col-2">Subject</th>
        <th class="col-1">Статус</th>
      </tr>
    </thead>
    <tbody class="table_body">
    {% for ticket in tickets %}
      {% if ticket.finished is True %}
      <tr class="success">
      {% else %}
      <tr class="danger">
      {% endif %}
        <td class="col-1">{{ ticket.id }}</td>
        <td class="col-1">{{ ticket.who }}</td>
        <td class="col-1">{{ ticket.where }}</td>
        <td class="col-1">{{ ticket.when }}</td>
        <td class="col-1">{{ ticket.date_end }}</td>
        <td class="col-2"><a href="{% url 'ticket:watch_one' ticket_id=ticket.id %}">{{ ticket.subject }}</a></td>
        {% if ticket.finished is True %}
            <td class="col-1">Готово</td>
        {% elif ticket.confirmed is True %}
            <td class="col-1">В работе</td>
        {% elif ticket.confirmed is False %}
            <td class="col-1">Не принята</td>
        {% endif %}
       </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

ticket/templates/thanks.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static '/css/57134.png' %}">
    <title>IT Support</title>

    <!-- Bootstrap core CSS -->
{#    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">#}
    <link rel="stylesheet" href="{% static '/css/ticket.css' %}">

</head>

{% block thanks %}

    <div class="spasibo">
        <p class="s1">Спасибо за обращение!</p>
        <p class="s2">Мы будем уведомлены о проблеме в кратчайшие сроки!</p>
        <a class="s3" href="/" type="button" class="btn btn-primary">На главную</a>
        <p class="s2">Отслеживать статус выполнения заявки Вы можете по <a href="{% url 'ticket:my_tickets' %}">ссылке</a></p>
    </div>

{% endblock %}

ticket/templates/tost.html
{% extends 'base.html' %}

{% block test %}

    <div align="center" style="background-color: #afd9ee">
{#        <form action="{% url 'cart:test_event_add' %}" method="post">#}
{#            <table>#}
{#                {% csrf_token %}#}
{#                {{ formset.as_p }}#}
{#            </table>#}
{#            <input class="btn btn-success" type="submit" value="Submit" />#}
{#        </form>#}
    <p>This is fucking SPAAAAARTA!</p>
    </div>
{% endblock %}

ticket/templates/watch_all.html
{% block watch_all %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>active</title>
    <link rel="stylesheet" href="{% static '/css/watch_all.css' %}">
  </head>
   
<div class=back_but>
    <a href="/"><input class="back" type="submit" value="Вернуться в главное меню"/></a>
</div>
<div class="container-fluid">
  <table class="table">
    <thead class="table_head">
      <tr>
        <th class="col-1">Номер</th>
        <th class="col-1">ID заявки</th>
        <th class="col-1">Отправитель</th>
        <th class="col-1">Место</th>
        <th class="col-1">Дата поступления</th>
        <th class="col-1">Дата завершения</th>
        <th class="col-2">Subject</th>
        <th class="col-1">Статус</th>
      </tr>
    </thead>
    <tbody class="table_body">
    {% for ticket in tickets %}
      {% if ticket.finished is True %}
      <tr class="success">
      {% else %}
      <tr class="danger">
      {% endif %}
        <td class="col-1">{{ forloop.counter }}</td>
        <td class="col-1">{{ ticket.id }}</td>
        <td class="col-1">{{ ticket.who }}</td>
        <td class="col-1">{{ ticket.where }}</td>
        <td class="col-1">{{ ticket.when }}</td>
        <td class="col-1">{{ ticket.date_end }}</td>
        <td class="col-2"><a href="{% url 'ticket:watch_one' ticket_id=ticket.id %}">{{ ticket.subject }}</a></td>
        {% if ticket.finished is True %}
            <td class="col-1">Готово</td>
        {% elif ticket.confirmed is True %}
            <td class="col-1">В работе!</td>
        {% elif ticket.confirmed is False %}
{#            <td class="col-1">not confirmed</td>#}
            <td class="col-1"><a href="{% url 'ticket:confirm' ticket_id=ticket.id %}">Принять</a></td>

        {% endif %}
       </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

ticket/templates/watch_one.html
{% block watch_all %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/watch_one.css' %}">
  </head>
<div class=back_but>
    <a href="{% url 'ticket:watch_all' %}"><input class="back" type="submit" value="Назад"/></a>
</div>
<div class="info">
    <p class="when">Дата поступления:{{ ticket.when }}</p>
    <p class="where">Отдел:{{ ticket.where }}</p>
    <p class="who">Имя:{{ ticket.who }}</p>
    <p class="confirmed">Принято:{{ ticket.confirmed }}</p>
    <p class="finished">Готово:{{ ticket.finished }}</p>
    <p class="ip">Адресс:{{ ticket.ip }}</p>
    <p class="subject"><strong>{{ ticket.subject }}</strong></p>
</div>
<div class="info">
    <form action="{% url 'ticket:finish' ticket_id=ticket.id %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="input-lg">
            <input type="text" name="rocket_user" placeholder="Имя и Фамилия в чате">
            {{ form.rocket_user.errors }}
            {{ form.rocket_user }}
            <input class="good button_ok" type="submit" value="Готово!">
        </div>
    </form>
</div>

<div class="button_ok">
    <a href="{% url 'ticket:finish' ticket_id=ticket.id %}" type="button" class="good">Готово!</a>
    <a href="{% url 'ticket:delete_row' ticket_id=ticket.id %}" type="button" class="delete">Архивировать.</a>
</div>


{% endblock %}