carts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from carts import views

app_name = 'cart'

urlpatterns = [
    url(r'^cart_home/$', views.home, name='cart_home'),
    url(r'^event_add/$', views.event_add, name='event_add'),
    # url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_status/(?P<status_id>[0-9]+)/$', views.watch_status, name='watch_status'),
    url(r'^watch_place/(?P<place_id>[0-9]+)/$', views.watch_place, name='watch_place'),
    url(r'^watch_model/(?P<model_id>[0-9]+)/$', views.watch_model, name='watch_model'),
    url(r'^homecoming/(?P<num_id>[0-9]+)/$', views.homecoming, name='homecoming'),
    url(r'^send_refill/(?P<num_id>[0-9]+)/$', views.send_refill, name='send_refill'),
    url(r'^test/$', TemplateView.as_view(template_name="test.html")),
    url(r'^cart_home/group_ops/$', views.group_ops, name='group_ops'),
    url(r'^cart_home/get_group_ops/$', views.get_group_ops, name='get_group_ops'),
    url(r'^cart_home/get_swap/$', views.get_swap, name='get_swap'),
    # url(r'^cart_home/get_swap/(?P<num>[0-9]+)/$', views.get_swap, name='get_swap'),
]

tickets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('loginsys.urls', namespace='loginsys')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^tickets/', include('ticket.urls')),
    url(r'^video/', views.you_tube, name='you_tube'),
    url(r'^macmap/', include('macmap.urls')),
    url(r'^', views.main),
] # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
# from django.utils import timezone


class Modell(models.Model):
    modell = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return str(self.modell)


class Num(models.Model):
    num = models.IntegerField(unique=True)
    modell = models.ForeignKey(Modell, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.num)


class Status(models.Model):
    status = models.CharField(max_length=25)

    def __str__(self):
        return str(self.status)


class Place(models.Model):
    place = models.CharField(max_length=40)

    def __str__(self):
        return str(self.place)


class Cartridge(models.Model):
    num = models.ForeignKey(Num, on_delete=models.PROTECT)
    fill_count = models.IntegerField(default=0)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    place = models.ForeignKey(Place, on_delete=models.PROTECT)
    last_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.num)


class Events(models.Model):
    date = models.DateTimeField(auto_now=True)
    num = models.ForeignKey(Num, on_delete=models.PROTECT)
    status = models.ForeignKey(Status, default=1, on_delete=models.PROTECT)
    place = models.ForeignKey(Place, on_delete=models.PROTECT)
    comment = models.TextField(max_length=200, blank=True)
    deleted = models.BooleanField(default=False)

#    class Meta:
#        get_latest_by = "date"
    def __str__(self):
        return str(self.status)

carts/forms.py
from django import forms
from django.forms import ModelForm


from carts.models import Events, Place, Cartridge


class Events_form(ModelForm):

    # place = forms.ModelChoiceField(queryset=Place.objects.all(),

    class Meta:
        model = Cartridge
        fields = ('num', 'status', 'place')


class Group_ops_form(forms.Form):
    nums = forms.CharField(label="nums", max_length=150)
    # cart_id = forms.CharField(label="cart_id", max_length=5)


class Swap_carts(forms.Form):
    nums = forms.CharField(label="nums", max_length=50)

carts/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context_processors import csrf
from carts.forms import Events_form, Group_ops_form, Swap_carts
from carts.models import Events, Cartridge, Num

'''
def home(request):
    return render_to_response('cart_home.html', {'events': Events.objects.all().order_by('-date')})
'''
# places
store = 1
fill_station = 2
# statuses
working = 1
at_home = 2
gone_away = 3

# Главная. Форма ввода и вывод последних событий
@login_required
def home(request):
    # form = Events_form
    args = {}
    args.update(csrf(request))
    args['form'] = Events_form
    args['swap_form'] = Swap_carts
    args['Cartridge'] = Cartridge.objects.all().order_by('-last_datetime')
    args['username'] = auth.get_user(request).username
    args['url_name'] = request.resolver_match.url_name  # Передает css классу "active" имя текущей вкладки
    return render_to_response('cart_home.html', args)


@login_required()
def event_add(request):
    try:
        if request.method == 'POST':
            form = Events_form(request.POST)
            if form.is_valid():  # Проверка валидности формы
                get_status = int(request.POST.get('status'))
                get_num = int(request.POST.get('num'))
                get_place = int(request.POST.get('place'))

                if get_status == at_home:  # Проверка на статус "Приехал"
                    count = Cartridge.objects.get(num=get_num)  # Выяснение текущего к-ва заправок
                    count = count.fill_count + 1  # Инкремент к-ва заправок
                    Cartridge.objects.update_or_create(
                        num_id=get_num,
                        defaults=dict(num_id=get_num,
                                      status_id=get_status,
                                      place_id=get_place,
                                      fill_count=count)
                    )
                else:
                    Cartridge.objects.update_or_create(
                        num_id=get_num,
                        defaults=dict(num_id=get_num,
                                      status_id=get_status,
                                      place_id=get_place)
                    )
                # event = Events(status_id=get_status, num_id=get_num, place_id=get_place)
                # event.save()  # Сохарнение записи в евенты
                # print("ok else")
    except:
        pass

    return HttpResponseRedirect('/carts/cart_home/')


def homecoming(request, num_id):
    try:
        count = Cartridge.objects.get(num=num_id)  # Выяснение текущего к-ва заправок
        count = count.fill_count + 1  # Добавление еще одного раза
        car = Cartridge.objects.get(num_id=num_id)
        car.status_id = at_home
        car.place_id = store
        car.fill_count = count
        car.save()
        event = Events(status_id=at_home, num_id=num_id, place_id=store)
        event.save()  # Сохранение записи в евенты
    except ObjectDoesNotExist:
        raise Http404

    return HttpResponseRedirect('/carts/cart_home/')


def send_refill(request, num_id):
    try:
        car = Cartridge.objects.get(num_id=num_id)
        car.status_id = gone_away
        car.place_id = fill_station
        car.save()
        event = Events(status_id=gone_away, num_id=num_id, place_id=fill_station)
        event.save()  # Сохранение записи в евенты
    except ObjectDoesNotExist:
        raise Http404

    return HttpResponseRedirect('/carts/cart_home/')


# Смотреть все картриджи одного статуса
def watch_status(request, status_id):
    args = {'status': Cartridge.objects.filter(status=status_id)}
    return render_to_response('watch_status.html', args)


# Смотреть об одном картридже
def watch_one_num(request, num_id):
    args = {'cart': Cartridge.objects.get(num_id=num_id)}
    return render_to_response('watch_one_num.html', args)


def watch_place(request, place_id):
    args = {'carts': Cartridge.objects.filter(place_id=place_id)}
    return render_to_response('watch_place.html', args)


def watch_model(request, model_id):
    args = {'carts': Cartridge.objects.filter(num_id=model_id)}
    return render_to_response('watch_model.html', args)


def test(request):
    return render_to_response('test.html')


def group_ops(request):
    form = Group_ops_form
    args = {}
    args.update(csrf(request))
    args['form'] = form
    return render_to_response('group_ops.html', args)


def get_group_ops(request):
    if request.method == 'POST':
        form = Group_ops_form(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            a = form.cleaned_data
            nums = a['nums'].split(',')
            for n in nums:
                try:
                    num_id = Num.objects.get(num=n).id
                    count = Cartridge.objects.get(num=num_id)  # Выяснение текущего к-ва заправок
                    count = count.fill_count + 1  # Добавление еще одного раза
                    car = Cartridge.objects.get(num_id=num_id)
                    car.status_id = at_home
                    car.place_id = store
                    car.fill_count = count
                    car.save()
                    event = Events(status_id=at_home, num_id=num_id, place_id=store)
                    event.save()  # Сохранение записи в евенты
                except ObjectDoesNotExist:
                    pass
    return HttpResponseRedirect('/carts/cart_home/')


def get_swap(request, **kwargs):
    if request.method == 'POST':
        form = Swap_carts(request.POST)
        if form.is_valid():
            a = form.cleaned_data
            # print(request.POST[Cartridge.num.id=""])
            print(a['nums'])
            b = request.GET.get('')
            print(b)
    return HttpResponseRedirect('/carts/cart_home/')

carts/templates/cart_home.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/cart_home.css' %}">
  </head>

{% block cart_event_form %}

<div class="navigator">
    <ul>
        <li>
            <a href="/"><input class="back" type="submit" value="Вернуться в главное меню"/></a>
        </li>
        <li>
            <a href="{% url 'cart:group_ops' %}"><input class="back" type="submit" value="Групповые операции"/></a>
        </li>
    </ul>
</div>    

    <div class="initial">
    
        <form action="{% url 'cart:event_add' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="input" >
                <label for="cart_number">Номер: </label>
                {{ form.num.errors }}
                {{ form.num }}
            </div>
            <div class="input">
                <label for="status">Статус: </label>
                {{ form.status.errors }}
                {{ form.status }}
            </div>
            <div class="input">
                <label for="place">Место: </label>
                {{ form.place.errors }}
                {{ form.place }}
            </div>
            <div class="but_send">
                <input class="subm" type="submit" value="Принять" />
            </div>
        </form>
  
    </div>



<div class="info">
    <table class="table">
        <thead class="table_head">
            <tr>
                <th class="coll-1">ID евента</th>
                <th>Дата</th>
                <th class="coll-1">Номер</th>
                <th>Статус</th>
                <th class="coll-1">Extra</th>
                <th>Swap</th>
                <th>Модель</th>
                <th>Место</th>
            </tr>
        </thead>
        {% for cart in Cartridge %}
            <tbody class="table_body">
                <tr>
                    <td class="coll-1">{{ cart.id }}</td>
                    <td>{{ cart.last_datetime }}</td>
                    <td class="coll-1"><a href="{% url 'cart:watch_one_num' num_id=cart.num_id %}">{{ cart.num }}</a></td>

                    <td><a href="{% url 'cart:watch_status' status_id=cart.status_id %}">{{ cart.status }}</a></td>
                    {% if cart.status_id == 1 %}
                        <td class="coll-1"><a class="btn-warning" href="{% url 'cart:send_refill' num_id=cart.num_id %}">На заправку!</a></td>
                    {% elif cart.status_id == 3%}
                        <td><a class="btn-success" href="{% url 'cart:homecoming' num_id=cart.num_id %}">На склад!</a></td>
                    {% else%}
                        <td>blank</td>
                    {% endif %}
                    <td>
                        <form action="{% url 'cart:get_swap'  %}?'car'={{ cart.num.id }}" method="post">
                            {% csrf_token %}
                            {{ swap_form.non_field_errors }}
                            {{ swap_form.nums }}
                            {{ kwargs.username }}
                            <input class="subm" type="submit" value="Swap">
                        </form>
                    </td>
                    <td><a href="{% url 'cart:watch_model' model_id=cart.num.modell_id %}">{{ cart.num.modell }}</a></td>
                    <td><a href="{% url 'cart:watch_place' place_id=cart.place_id %}">{{ cart.place }}</a></td>
                </tr>
            </tbody>
        {% endfor %}
    </table>
</div>


{% endblock %}

carts/templates/group_ops.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/cart_home.css' %}">
  </head>


<div class="navigator">
    <ul>
        <li>
            <a href="{% url 'cart:cart_home' %}"><input class="back" type="submit" value="Вернуться в картриджи"/></a>
        </li>
    </ul>
</div> 

{% block group_ops %}

    <div class="form-group">
        <form action="{% url 'cart:get_group_ops' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div>
                <label for="cart_numbers">Номера</label>
                {{ form.non_field_errors }}
                {{ form.nums }}
            </div>
            <input class="subm" type="submit" value="Приехать" />
        </form>
    </div>

{% endblock %}

carts/templates/test.html
{% extends 'main.html' %}

{% block test %}

    <div align="center" style="background-color: #afd9ee">
{#        <form action="{% url 'cart:test_event_add' %}" method="post">#}
{#            <table>#}
{#                {% csrf_token %}#}
{#                {{ formset.as_p }}#}
{#            </table>#}
{#            <input class="btn btn-success" type="submit" value="Submit" />#}
{#        </form>#}
    <p>This is fucking SPAAAAARTA!</p>
    <p>Here is just cruel</p>
    </div>
{% endblock %}

carts/templates/watch_cart_status.html
{% extends 'base.html' %}

{% block watch_cart_status %}

    <p>test</p>


{% endblock %}

carts/templates/watch_model.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/cart_home.css' %}">
  </head>

<div class="navigator">
    <ul>
        <li>
            <a href="{% url 'cart:cart_home' %}"><input class="back" type="submit" value="Вернуться в картриджи"/></a>
        </li>
    </ul>
</div> 

{% block watch_model %}
<div class="container-fluid">
    <table class="table">
        <thead class="table_head">
            <tr>
                <th class="col-md-3">Дата</th>
                <th class="col-md-3">Номер</th>
                <th class="col-md-3">Место</th>
                <th class="col-md-3">Статус</th>
            </tr>
        </thead>
    {% for cart in carts %}
        <tbody class="table_body">
            <tr>
                <td class="col-md-3">{{ cart.last_datetime }}</td>
                <td class="col-md-3">{{ cart.num }}</td>
                <td class="col-md-3">{{ cart.place }}</td>
                <td class="col-md-3">{{ cart.status }}</td>
            </tr>
        </tbody>
    {% endfor %}
    </table>
</div>
{% endblock %}

carts/templates/watch_one_num.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/cart_home.css' %}">
  </head>

{% block watch_one_num %}
<div class="navigator">
    <ul>
        <li>
            <a href="{% url 'cart:cart_home' %}"><input class="back" type="submit" value="Вернуться в картриджи"/></a>
        </li>
    </ul>
</div> 

<div class="container-fluid">
    <table class="table">
        <thead class="table_head">
            <tr>
                <th class="col-md-3">Дата</th>
                <th class="col-md-3">Номер</th>
                <th class="col-md-3">Место</th>
                <th class="col-md-3">Статус</th>
            </tr>
        </thead>
        <tbody class="table_body">
            <tr>
                <td class="col-md-3">{{ cart.last_datetime }}</td>
                <td class="col-md-3">{{ cart.num }}</td>
                <td class="col-md-3">{{ cart.place }}</td>
                <td class="col-md-3">{{ cart.status }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

carts/templates/watch_place.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/cart_home.css' %}">
  </head>

<div class="navigator">
    <ul>
        <li>
            <a href="{% url 'cart:cart_home' %}"><input class="back" type="submit" value="Вернуться в картриджи"/></a>
        </li>
    </ul>
</div>

{% block watch_place %}
<div class="container-fluid">
    <table class="table">
        <thead class="table_head">
            <tr>
                <th class="col-md-3">Дата</th>
                <th class="col-md-3">Номер</th>
                <th class="col-md-3">Место</th>
                <th class="col-md-3">Статус</th>
            </tr>
        </thead>
    {% for cart in carts %}
        <tbody class="table_body">
            <tr>
                <td class="col-md-3">{{ cart.last_datetime }}</td>
                <td class="col-md-3">{{ cart.num }}</td>
                <td class="col-md-3">{{ cart.place }}</td>
                <td class="col-md-3">{{ cart.status }}</td>
            </tr>
        </tbody>
    {% endfor %}
    </table>
</div>
{% endblock %}

carts/templates/watch_status.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static '/css/cart_home.css' %}">
  </head>


<div class="navigator">
    <ul>
        <li>
            <a href="{% url 'cart:cart_home' %}"><input class="back" type="submit" value="Вернуться в картриджи"/></a>
        </li>
    </ul>
</div> 

{% block watch_status %}
<div class="container-fluid">
    <table class="table">
        <thead class="table_head">
            <tr>
                <th class="col-md-3">Дата</th>
                <th class="col-md-2">Номер</th>
                <th class="col-md-3">Место</th>
                <th class="col-md-3">Статус</th>
{#                <th class="col-md-1">Extra</th>#}
            </tr>
        </thead>
    {% for stat in status %}
        <tbody class="table_body">
            <tr>
                <td class="col-md-3">{{ stat.last_datetime }}</td>
                <td class="col-md-2">{{ stat.num }}</td>
                <td class="col-md-3">{{ stat.place }}</td>
                <td class="col-md-3">{{ stat.status }}</td>
{#                <td class="col-md-1">#}
{#                    <a href="{% url 'cart:homecoming' num_id=event.num_id %}">Приехать</a>#}
{#                </td>#}
            </tr>
        </tbody>
    {% endfor %}
    </table>
</div>
{% endblock %}

carts/templates/you_tube.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>SUPPORT</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
  </head> 
  <body>
  	
Привет мир







  </body>

  </html>