carts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from carts import views

app_name = 'cart'

urlpatterns = [
    url(r'^cart_home/$', views.home, name='cart_home'),
    url(r'^event_add/$', views.event_add, name='event_add'),
    # url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_status/(?P<status_id>[0-9]+)/$', views.watch_status, name='watch_status'),
    url(r'^watch_place/(?P<place_id>[0-9]+)/$', views.watch_place, name='watch_place'),
    url(r'^watch_model/(?P<model_id>[0-9]+)/$', views.watch_model, name='watch_model'),
    url(r'^homecoming/(?P<num_id>[0-9]+)/$', views.homecoming, name='homecoming'),
    url(r'^send_refill/(?P<num_id>[0-9]+)/$', views.send_refill, name='send_refill'),
    url(r'^test/$', TemplateView.as_view(template_name="test.html")),
    url(r'^cart_home/group_ops/$', views.group_ops, name='group_ops'),
    url(r'^cart_home/get_group_ops/$', views.get_group_ops, name='get_group_ops'),
    url(r'^cart_home/get_swap/$', views.get_swap, name='get_swap'),
    # url(r'^cart_home/get_swap/(?P<num>[0-9]+)/$', views.get_swap, name='get_swap'),
]

loginsys/urls.py
from django.conf.urls import url

from loginsys import views

app_name = 'loginsys'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register')
]

tickets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('loginsys.urls', namespace='loginsys')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^tickets/', include('ticket.urls')),
    url(r'^video/', views.you_tube, name='you_tube'),
    url(r'^macmap/', include('macmap.urls')),
    url(r'^', views.main),
] # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginsys/views.py
from django.shortcuts import render_to_response, redirect
from django.template.context_processors import csrf
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm


def login(request):
    args = {}
    args.update(csrf(request))
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        return redirect('/')
    else:
        args['login_error'] = "Пользователь не найден"
        return render_to_response('login.html', args)


def logout(request):
    auth.logout(request)
    return redirect('/')

def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    if request.POST:
        newUserForm = UserCreationForm(request.POST)
        if newUserForm.is_valid():
            newUserForm.save()
            newuser = auth.authenticate(username=newUserForm.cleaned_data['username'],
                                        password=newUserForm.cleaned_data['password2'])
            auth.login(request, newuser)
            return redirect('/home/')
        else:
            args['form'] = newUserForm
    return render_to_response('register.html', args)

loginsys/templates/login.html
{% extends 'base.html' %}

{% block login %}
    <div class="container" style="width: 30%">

      <form action="{% url 'loginsys:login'  %}" method="post" >
          {% csrf_token %}
        <h2 class="form-signin-heading">Авторизация</h2>
        <label for="username" class="sr-only">Username</label>
        <input type="text" name="username" id="username" class="form-control" placeholder="Username" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Password">

        <button class="btn btn-lg btn-primary center" type="submit">Вход</button>
          <div class="btn center"><a href="{% url 'loginsys:register' %}">Регистрация</a></div>
{#        <a class="btn btn-lg btn-default center" href="login.html">Регистрация</a>#}
      </form>
    </div>
{% endblock %}

loginsys/templates/register.html
{% extends 'base.html' %}

{% block register %}
    <div class="container" style="width: 30%">

      <form action="{% url 'loginsys:register'  %}" method="post" >
          {% csrf_token %}
          {{ form }}

        <input class="btn btn-lg btn-primary center" type="submit">"Зарегистрироваться">
      </form>
    </div>
{% endblock %}