carts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from carts import views

app_name = 'cart'

urlpatterns = [
    url(r'^cart_home/$', views.home, name='cart_home'),
    url(r'^event_add/$', views.event_add, name='event_add'),
    # url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_one_num/(?P<num_id>[0-9]+)/$', views.watch_one_num, name='watch_one_num'),
    url(r'^watch_status/(?P<status_id>[0-9]+)/$', views.watch_status, name='watch_status'),
    url(r'^watch_place/(?P<place_id>[0-9]+)/$', views.watch_place, name='watch_place'),
    url(r'^watch_model/(?P<model_id>[0-9]+)/$', views.watch_model, name='watch_model'),
    url(r'^homecoming/(?P<num_id>[0-9]+)/$', views.homecoming, name='homecoming'),
    url(r'^send_refill/(?P<num_id>[0-9]+)/$', views.send_refill, name='send_refill'),
    url(r'^test/$', TemplateView.as_view(template_name="test.html")),
    url(r'^cart_home/group_ops/$', views.group_ops, name='group_ops'),
    url(r'^cart_home/get_group_ops/$', views.get_group_ops, name='get_group_ops'),
    url(r'^cart_home/get_swap/$', views.get_swap, name='get_swap'),
    # url(r'^cart_home/get_swap/(?P<num>[0-9]+)/$', views.get_swap, name='get_swap'),
]

loginsys/urls.py
from django.conf.urls import url

from loginsys import views

app_name = 'loginsys'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register')
]

ticket/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from ticket import views

app_name = 'ticket'

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^thanks/$', TemplateView.as_view(template_name="thanks.html")),
    url(r'^test/$', views.test, name='test'),
    url(r'^delete_row/(?P<ticket_id>[0-9]+)/$', views.delete_row, name='delete_row'),
    url(r'^all/$', views.watch_all, name='watch_all'),
    url(r'^my_tickets/$', views.my_tickets, name='my_tickets'),
    url(r'^watch/(?P<ticket_id>[0-9]+)/$', views.watch_one, name='watch_one'),
    url(r'^history/$', views.history, name='history'),
    url(r'^ticket_add/$', views.send_ticket, name='ticket_add'),
    url(r'^finish/(?P<ticket_id>[0-9]+)/$', views.finish, name='finish'),
    url(r'^confirm/(?P<ticket_id>[0-9]+)/$', views.confirm, name='confirm'),
]

tickets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('loginsys.urls', namespace='loginsys')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^tickets/', include('ticket.urls')),
    url(r'^video/', views.you_tube, name='you_tube'),
    url(r'^macmap/', include('macmap.urls')),
    url(r'^', views.main),
] # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.contrib import auth

from ticket.models import Tickets


def main(request):
    args = {}
    args['username'] = auth.get_user(request).username
    args['url_name'] = request.resolver_match.url_name
    args['new_tickets'] = len(Tickets.objects.filter(confirmed=False))  # к-во незавершенных заявок
    args['not_finished'] = len(Tickets.objects.filter(finished=False))  # к-во незавершенных заявок
    return render_to_response("main.html", args)


def you_tube(request):
    return render_to_response("you_tube.html")

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static '/css/57134.png' %}"<!--"../../../favicon.ico">
    <title>Support</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/ticket.css' %}">
    <link rel="stylesheet" href="{% static '/css/contact.css' %}">

</head>

<body>
    <header>
      <ul class="nav nav-tabs">
            <li class="send_ticket{% if url_name == 'home' %}active{% endif %}">
                <a href="{% url 'ticket:home' %}">Отправить заявку</a>
            </li>
            {% if username == 'mjee' %}
                <li class="{% if url_name == 'watch_all' %}active{% endif %}">
                    <a href="{% url 'ticket:watch_all' %}">Смотреть все</a>
                </li>
                <li class="{% if url_name == 'history' %}active{% endif %}">
                    <a href="{% url 'ticket:history' %}">Архив</a>
                </li>
                <li class="{% if url_name == 'cart_home' %}active{% endif %}">
                    <a href="{% url 'cart:cart_home' %}">Картриджи</a>
                </li>
                <li class="nav nav-tabs; pull-right">
                    <a href="{% url 'loginsys:logout' %}">logout {{ username }}</a>
                </li>
            {% endif %}
            {% if username %}
            <li class="nav nav-tabs; pull-right">
                <a href="{% url 'loginsys:logout' %}">logout {{ username }}</a>
            </li>
            {% elif not username %}
                <li class="nav nav-tabs; pull-right">
                    <a href="{% url 'loginsys:login' %}">login</a>
                </li>
            {% endif %}
        </ul>  
    </header>

{#<div>#}
{#    {% if username %}#}
{#        <p>Logged</p>#}
{#    {% else %}#}
{#        <p>Nonlogged</p>#}
{#    {% endif %}#}
{#</div>#}

{% block watch_all %}{% endblock %}
{% block cart_event_form %} {% endblock %}
{% block form %}{% endblock %}
{% block watch_one %}{% endblock %}
{% block login %}{% endblock %}
{% block thanks %}{% endblock %}
{% block test %}{% endblock %}
{% block watch_one_num %}{% endblock %}
{% block watch_status %}{% endblock %}
{% block watch_place %}{% endblock %}
{% block watch_model %}{% endblock %}
{% block group_ops %}{% endblock %}
{% block register %}{% endblock %}
{% block uploadPic %}{% endblock %}
{% block my_tickets %}{% endblock %}

<footer class="navbar-fixed-bottom text-center">
{#    <p class="inline-group">Copyright Zarechniy 2017</p>#}
</footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/main.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>IT Support</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
  </head> 
  <body>
  <div class="main_menu"></div> 

<div class="navigator">
    {% if username == 'mjee' %}
        {% if not_finished > 0 %}
            <div class="tickets_not_finished">
                <a href="{% url 'ticket:watch_all' %}"> {{ not_finished }}</a>
            </div>
        {% endif %}
    {% if new_tickets > 0 %}
            <div class="tickets_ready">
                <a href="{% url 'ticket:watch_all' %}"> {{ new_tickets }}</a>
            </div>
        {% endif %}
    {% endif %}

        <ul class="nav">
            {% if username == 'mjee' %}
                <li class="list">
                    <a href="{% url 'ticket:watch_all' %}">Активные заявки</a>
                </li>

                <li>
                    <a href="{% url 'ticket:history' %}">Архив заявок</a>
                </li>
                <li>
                    <a href="{% url 'cart:cart_home' %}">Картриджи</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'ticket:my_tickets' %}">Мои заявки</a>
                </li>
            {% endif %}
                <li>
                    <a href="{% url 'you_tube' %}"> Видео </a>
                </li>
            {% if username %}
            	<li class="">
               		 <a href="{% url 'loginsys:logout' %}">Выйти</a>
           		 </li>
            {% elif not username %}
                <li class="login">
                    <a href="{% url 'loginsys:login' %}">Login</a>
                </li>
            {% endif %}
        </ul> 

{#<div>#}
{#    {% if username %}#}
{#        <p>Logged</p>#}
{#    {% else %}#}
{#        <p>Nonlogged</p>#}
{#    {% endif %}#}
{#</div>#}

{% block watch_all %}{% endblock %}
{% block cart_event_form %} {% endblock %}
{% block form %}{% endblock %}
{% block watch_one %}{% endblock %}
{% block login %}{% endblock %}
{% block thanks %}{% endblock %}
{% block test %}{% endblock %}
{% block watch_one_num %}{% endblock %}
{% block watch_status %}{% endblock %}
{% block watch_place %}{% endblock %}
{% block watch_model %}{% endblock %}
{% block group_ops %}{% endblock %}
{% block register %}{% endblock %}
{% block uploadPic %}{% endblock %}
{% block my_tickets %}{% endblock %}
</div>

</body>

    <div class="footer">
            <div class="tecket">
                <a href="/tickets/">
                    <input class="btn_msg_send" type="submit" value="Отправить заявку в it"/>
                </a>
            </div>
            <div class="logo"></div>
            <div class="contact">
                <a href="/contacts/">
                    <input class="btn_msg_send" type="submit" value="Адресная книга"/>
                </a>
            </div>
    </div>

</html>

templates/you_tube.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>youtube</title>
    <link rel="stylesheet" href="{% static '/css/you_tube.css' %}">
    <link rel="stylesheet" href="{% static '/css/history.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
  </head> 
  <body>
    <div class="back_but">
    <a href="/"><input class="back" type="submit" value="Вернуться в главное меню"/></a>
    </div>

<div class="video">
   <div class="video_head">ANSERGLOB - 24 роки!</div>
<div class="video-container">
   <iframe width="560" height="315" src="https://www.youtube.com/embed/U2RWeb-0F0U" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div> 
    <div class="video_info">Кожен наш День народження – свято всього колективу! Ми пишаємося тим, що ми – справжня команда. Команда, яка з задоволенням разом працює, вдосконалюється, навчається та відпочиває! Саме тому ми впевнені у своїх подальших успіхах та раді йти до нових перемог разом! Ми звикли пишатися досягненнями один одного та всієї команди ANSERGLOB!</div>
</div> 
  
<div class="video">
  <div class="video_head">ANSERGLOB - AXIOM OF QUALITY</div>
  	<div class="video-container">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/-zL9SoyOIBE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
   <div class="video_info">Відео про торгову марку ANSERGLOB - українського виробника будівельних матеріалів незмінно високої якості. Ви можете побачити як створюють матеріали від розробки у лабораторії до виробництва.</div>
</div>   

<div class="video">
  <div class="video_head">ANSERGLOB вітає з Днем Прапора України</div>
<div class="video-container">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/9ztgDqZUoJE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<div class="video_info">Колектив групи компаній ANSERGLOB вітає з Днем Прапора та Днем Незалежності України!
    Кожен рік на День Державного Прапора України ми урочисто підіймаємо новий прапор України перед нашим офісом, щоб кожен день він спонукав нас на нові досягнення і звершення!</div>
</div>
<div class="video">
   <div class="video_head">День народження ANSERGLOB 2018</div>
<div class="video-container">
   <iframe width="560" height="315" src="https://www.youtube.com/embed/xO02MBu3NGE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div> 
    <div class="video_info">Відео з нашего 22-го дня народження! Дякуємо усім, хто нас обирає! Ми вдосконалюємось для Вас!</div>
</div>
<div class="video">
   <div class="video_head">Поздоровлення від Житомирської філіі ТМ ANSERGLOB</div>
<div class="video-container">
   <iframe width="560" height="315" src="https://www.youtube.com/embed/6UU-g00vEbE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div> 
    <div class="video_info"></div>
</div> 

<div class="video">
   <div class="video_head">TM ANSERGLOB приняла вызов от компании АКВИЛОН</div>
<div class="video-container">
   <iframe width="560" height="315" src="https://www.youtube.com/embed/aB8Pmqc8JPk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div> 
    <div class="video_info">ТМ ANSERGLOB начала поддержку украинской армии задолго до того, как флешмоб ice bucket challenge обрел свою популярность.</div>
</div> 
 
<div class="video">
   <div class="video_head">20-летие ANSERGLOB</div>
<div class="video-container">
   <iframe width="560" height="315" src="https://www.youtube.com/embed/YXUXVXhcfp0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div> 
    <div class="video_info">Ролик посвященный празднованию 20-летия ANSERGLOB</div>
</div> 


  





  	
  </body>

  </html>